# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'AFNetworking'
pod 'DACircularProgress'
pod 'pop', :git => 'https://github.com/facebook/pop.git'

end
